import Link from 'next/link'
import { createClient } from '@/lib/supabase/server'
import { setOpportunityStatus, createOpportunity } from './actions'

export default async function AdminOpportunitiesPage(){
 const supabase=await createClient(); const {data:{user}}=await supabase.auth.getUser(); if(!user) return <></>
 const {data:p}=await supabase.from('profiles').select('role').eq('id',user.id).maybeSingle(); if(!p?.role||!['admin','super_admin','content_manager'].includes(p.role)) return <main className="section"><div className="glass section"><h1>Restricted.</h1><Link className="btn" href="/app">Back</Link></div></main>
 const {data:opps}=await supabase.from('opportunities').select('id,title,sponsor_name,description,reward_amount,token,duration_minutes,budget_remaining,status,created_at').order('created_at',{ascending:false})
 return <main className="main" style={{paddingTop:32}}><div className="topbar"><div><div className="eyebrow">Admin · Rewards</div><h1>Opportunity management.</h1></div><Link className="btn secondary" href="/admin">Back</Link></div>
 <section className="glass section"><div className="section-head"><h3>Create opportunity</h3><span className="muted">Starts as draft</span></div><form action={createOpportunity} style={{display:'grid',gap:10}}><input className="input" name="sponsorName" placeholder="Sponsor name" required/><input className="input" name="title" placeholder="Title" required/><textarea className="input" name="description" placeholder="Description" required/><div className="grid"><input className="input" name="rewardAmount" type="number" min="1" placeholder="Reward (minor units)" required/><input className="input" name="budgetRemaining" type="number" min="1" placeholder="Budget (minor units)" required/></div><select className="input" name="token" defaultValue="USDC"><option>USDC</option><option>USDT</option><option>USDM</option></select><input className="input" name="durationMinutes" type="number" min="1" defaultValue="5"/><button className="btn" type="submit">Create draft</button></form></section>
 <section className="glass section" style={{marginTop:18}}><div className="section-head"><h3>Existing opportunities</h3><span className="muted">{opps?.length ?? 0} total</span></div>{(opps??[]).map(o=><div className="opp" key={o.id}><div style={{minWidth:0}}><strong>{o.title}</strong><div className="muted" style={{fontSize:11,marginTop:4}}>{o.sponsor_name} · {(Number(o.reward_amount)/100).toFixed(2)} {o.token} · budget {(Number(o.budget_remaining)/100).toFixed(2)}</div></div><form action={setOpportunityStatus} style={{display:'flex',gap:6,alignItems:'center'}}><input type="hidden" name="opportunityId" value={o.id}/><select className="input" name="status" defaultValue={o.status}><option>draft</option><option>active</option><option>paused</option><option>completed</option><option>expired</option></select><button className="btn secondary" type="submit">Save</button></form></div>)}</section></main>
}
