import Link from 'next/link'
import { ArrowUpRight, Flame, ShieldCheck, Sparkles, Users, Zap } from 'lucide-react'
import { TopActions } from '@/components/app-shell'
import { createClient } from '@/lib/supabase/server'

export default async function DashboardPage() {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  const [{ data: profile }, { data: opportunities }, { data: threads }, { data: wallet }, { data: rig }] = await Promise.all([
    user ? supabase.from('profiles').select('full_name,username,trust_score').eq('id',user.id).maybeSingle() : Promise.resolve({data:null}),
    supabase.from('opportunities').select('id,title,reward_amount,duration_minutes,sponsor_name').eq('status','active').order('created_at',{ascending:false}).limit(3),
    supabase.from('threads').select('id,title,body,created_at,profiles!threads_author_id_fkey(full_name,username)').eq('status','published').order('created_at',{ascending:false}).limit(2),
    user ? supabase.rpc('get_wallet_summary') : Promise.resolve({data:null}),
    user ? supabase.from('rigs').select('current_hash_rate,config').eq('user_id',user.id).order('created_at',{ascending:true}).limit(1).maybeSingle() : Promise.resolve({data:null}),
  ])
  const walletRow = Array.isArray(wallet) ? wallet[0] : wallet
  const config = (rig?.config ?? {}) as Record<string,unknown>
  const heat = Number(config.heat ?? 0)
  const hash = Number(rig?.current_hash_rate ?? 0)
  const trust = Number(profile?.trust_score ?? 0)
  return <>
    <header className="topbar"><div><div className="eyebrow">NEXORA · live</div><h1>{profile?.full_name ? `Good morning, ${profile.full_name}.` : 'Good morning, Nexorian.'}</h1></div><TopActions /></header>
    <section className="glass hero"><div><div className="eyebrow">Trust-first discovery</div><h2>One place to discover, earn and build.</h2><p>NEXORA connects community conversations with verified opportunities and a virtual mining game. Rewards are transparent, wallet activity is ledger-based, and game state is stored server-side.</p><div className="hero-actions"><Link className="btn" href="/app/earn">Explore opportunities <ArrowUpRight size={16}/></Link><Link className="btn secondary" href="/app/mining">Open mining rig</Link></div></div><div className="glass" style={{padding:20,alignSelf:'stretch',position:'relative',zIndex:1}}><div style={{display:'flex',justifyContent:'space-between'}}><span className="muted">Trust score</span><ShieldCheck size={19}/></div><div style={{fontSize:48,fontWeight:800,letterSpacing:'-.06em',marginTop:14}}>{trust}</div><div className="meter"><span style={{width:`${Math.min(100,trust)}%`}} /></div><p className="muted" style={{fontSize:12,lineHeight:1.6}}>Calculated from the authenticated profile and verified activity.</p></div></section>
    <section className="stats"><div className="glass stat"><div className="muted">Available balance</div><div className="value">${(Number(walletRow?.available_amount ?? 0)/100).toFixed(2)}</div><div className="muted" style={{fontSize:11}}>USDC · ledger-backed</div></div><div className="glass stat"><div className="muted">Lifetime earned</div><div className="value">${(Number(walletRow?.lifetime_earned ?? 0)/100).toFixed(2)}</div><div className="muted" style={{fontSize:11}}>verified rewards</div></div><div className="glass stat"><div className="muted">Mining rate</div><div className="value">{hash ? `${(hash/1000000).toFixed(2)} MH/s` : 'No rig'}</div><div className="muted" style={{fontSize:11}}>{hash ? `heat ${heat.toFixed(0)}%` : 'create your rig'}</div></div></section>
    <div className="grid"><section className="glass section"><div className="section-head"><h3>Recent community</h3><Link className="muted" href="/app/explore" style={{fontSize:12}}>See all</Link></div><div className="feed">{(threads ?? []).map((thread:any) => <article className="thread" key={thread.id}><div className="thread-head"><div className="avatar">{(thread.profiles?.full_name ?? thread.profiles?.username ?? 'NX').slice(0,2).toUpperCase()}</div><div><strong style={{fontSize:13}}>{thread.profiles?.full_name ?? thread.profiles?.username ?? 'Nexorian'}</strong><div className="muted" style={{fontSize:11}}>community</div></div></div><div className="thread-title">{thread.title}</div><div className="thread-copy">{thread.body}</div></article>)}</div>{(threads ?? []).length===0 && <div className="muted">No published threads yet.</div>}</section><div><section className="glass section"><div className="section-head"><h3>Verified opportunities</h3><Link className="muted" href="/app/earn" style={{fontSize:12}}>View all</Link></div>{(opportunities ?? []).map(o => <div className="opp" key={o.id}><div><strong style={{fontSize:13}}>{o.title}</strong><div className="muted" style={{fontSize:11,marginTop:4}}>{o.duration_minutes} min · {o.sponsor_name}</div></div><div className="reward">+${(Number(o.reward_amount)/100).toFixed(2)}</div></div>)}</section><section className="glass mining-card"><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><div><div className="eyebrow">Mining state</div><h3 style={{margin:'6px 0'}}>{rig ? 'Crystal Caverns' : 'No rig yet'}</h3></div><Flame size={20}/></div><div className="mining-grid"><div className="mining-stat"><div className="muted" style={{fontSize:11}}>Hash rate</div><strong>{hash ? `${(hash/1000000).toFixed(2)} MH/s` : '—'}</strong></div><div className="mining-stat"><div className="muted" style={{fontSize:11}}>Thermal</div><strong>{rig ? `${heat.toFixed(0)}%` : '—'}</strong></div></div><div style={{display:'flex',gap:8,marginTop:16,alignItems:'center',fontSize:12}}><Zap size={15}/><span className="muted">{rig ? 'Server-side rig state' : 'Create a rig to start mining'}</span></div></section></div></div><div style={{display:'flex',gap:18,marginTop:18,flexWrap:'wrap'}}><span className="muted" style={{fontSize:11}}><Users size={13}/> Live community data</span><span className="muted" style={{fontSize:11}}><Sparkles size={13}/> {opportunities?.length ?? 0} verified opportunities shown</span></div>
  </>
}
