import Link from 'next/link'
import { createAdminClient } from '@/lib/supabase/admin'
import { getAdminIdentity } from '@/lib/admin-auth'
import { transitionWithdrawal } from './actions'

export default async function AdminWithdrawalsPage(){
 const identity=await getAdminIdentity()
 if(!identity) return <main className="section"><div className="glass section"><h1>Restricted.</h1><Link className="btn" href="/login?mode=user_id">Sign in</Link></div></main>
 if(!['admin','super_admin','finance_admin'].includes(identity.role)) return <main className="section"><div className="glass section"><h1>Restricted.</h1><Link className="btn" href="/app">Back</Link></div></main>
 const db=createAdminClient(); const {data:rows}=await db.from('withdrawals').select('id,user_id,amount,token,wallet_address,status,created_at,provider_reference').in('status',['pending','processing']).order('created_at',{ascending:true})
 const applyTransition=async(formData:FormData)=>{ 'use server'; await transitionWithdrawal(formData) }
 return <main className="main" style={{paddingTop:32}}><div className="topbar"><div><div className="eyebrow">Admin · Finance</div><h1>Withdrawal queue.</h1><div className="muted" style={{fontSize:12}}>{identity.username ?? identity.full_name ?? 'Administrator'}</div></div><Link className="btn secondary" href="/admin">Back</Link></div><section className="glass section"><div className="notice">Money movement must be backed by a verified Celo transaction. Completed withdrawals require a transaction hash.</div><div style={{display:'grid',gap:10,marginTop:18}}>{(rows??[]).map((w:any)=><article className="opp" key={w.id}><div style={{minWidth:0,flex:1}}><strong>{(Number(w.amount)/100).toFixed(2)} {w.token}</strong><div className="muted" style={{fontSize:11,marginTop:4}}>User {w.user_id.slice(0,8)}… · {w.wallet_address}</div><div className="muted" style={{fontSize:11,marginTop:3}}>Created {new Date(w.created_at).toLocaleString()} · {w.status}</div>{w.provider_reference&&<div className="muted" style={{fontSize:11,marginTop:3}}>Tx: {w.provider_reference}</div>}</div><form action={applyTransition} style={{display:'flex',gap:6,alignItems:'center',flexWrap:'wrap',justifyContent:'flex-end'}}><input type="hidden" name="withdrawalId" value={w.id}/><input className="input" name="providerReference" placeholder="confirmed Celo tx hash" required/><select className="input" name="status" defaultValue="processing"><option>processing</option><option>completed</option><option>failed</option><option>reversed</option></select><button className="btn secondary" type="submit">Apply</button></form></article>)}{(rows??[]).length===0&&<div className="muted">No pending withdrawals.</div>}</div></section></main>
}
