import Link from 'next/link'
import { login, signup } from './actions'

export default async function LoginPage({ searchParams }: { searchParams?: Promise<Record<string,string|undefined>> }) {
  const params = searchParams ? await searchParams : {}
  const mode = params.mode === 'user_id' ? 'user_id' : 'email'
  const error = params.error
  return <main className="login-shell"><section className="glass login-card"><div className="brand" style={{padding:'0 0 22px'}}><span className="brand-mark"/>NEXORA</div><div className="eyebrow">Secure access</div><h1 style={{fontSize:32,marginBottom:8}}>Welcome back.</h1><p className="muted" style={{lineHeight:1.6}}>{mode === 'email' ? 'Sign in with your email and password.' : 'Sign in with your administrator-issued User ID and password.'} Sessions are stored in secure HTTP-only cookies.</p><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:8,margin:'18px 0'}}><Link className={mode==='email'?'btn':'btn secondary'} href="/login">Email</Link><Link className={mode==='user_id'?'btn':'btn secondary'} href="/login?mode=user_id">User ID</Link></div>{error && <div className="notice" style={{marginBottom:14}}>Unable to sign in. Check your credentials and try again.</div>}
  {mode==='email' ? <form><div className="field"><label htmlFor="email">Email</label><input id="email" name="email" type="email" required autoComplete="email"/></div><div className="field"><label htmlFor="password">Password</label><input id="password" name="password" type="password" required minLength={8} autoComplete="current-password"/></div><div style={{display:'grid',gap:10,marginTop:18}}><input type="hidden" name="mode" value="email"/><button className="btn" formAction={login}>Log in</button><button className="btn secondary" formAction={signup}>Create account</button></div></form> : <form><div className="field"><label htmlFor="userId">User ID</label><input id="userId" name="userId" type="text" required minLength={4} maxLength={32} pattern="[A-Za-z0-9][A-Za-z0-9._-]{3,31}" autoComplete="username" placeholder="Administrator-issued User ID"/></div><div className="field"><label htmlFor="password">Password</label><input id="password" name="password" type="password" required minLength={10} autoComplete="current-password"/></div><input type="hidden" name="mode" value="user_id"/><button className="btn" style={{marginTop:18}} formAction={login}>Log in with User ID</button></form>}
  <p className="footer-note">Manual User ID accounts are created by authorized NEXORA administrators. They are not public sign-up accounts.</p></section></main>
}
